name: Go

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -o build/linux/tmblrscore main.go
        GOOS=windows GOARCH=amd64 go build -o build/windows/tmblrscore.exe main.go
        GOOS=darwin GOARCH=amd64 go build -o build/macos/tmblrscore main.go

    - name: Archive
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        (cd build/linux && tar cfvz ../tmblrscore-linux-amd64.tar.gz tmblrscore)
        (cd build/windows && tar cfvz ../tmblrscore-windows-amd64.tar.gz tmblrscore.exe)
        (cd build/macos && tar cfvz ../tmblrscore-darwin-amd64.tar.gz tmblrscore)

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}